// products/react-admin/apps/logistics-app/src/components/btc-file-thumbnail-cell/BtcFileThumbnailCell.tsx
import React, { useState, useMemo } from 'react';
import ReactDOM from 'react-dom';
import { Button } from '@enterprise-workspace/frontend/shared';
import {
  FileExcelOutlined,
  FilePptOutlined,
  FileWordOutlined,
  FilePdfOutlined,
  FileTextOutlined,
  FileOutlined,
} from '@ant-design/icons';
import styles from './BtcFileThumbnailCell.module.scss';

const Z_INDEX = 4000;

interface BtcFileThumbnailCellProps {
  src?: string;
  mime?: string;
  originalName?: string;
}

interface ImagePreviewProps {
  visible: boolean;
  src: string;
  onClose: () => void;
}

const ImagePreview: React.FC<ImagePreviewProps> = ({ visible, src, onClose }) => {
  if (!visible) return null;

  const handleBackdropClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      onClose();
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') {
      onClose();
    }
  };

  React.useEffect(() => {
    if (visible) {
      document.body.style.overflow = 'hidden';
      document.addEventListener('keydown', handleKeyDown);
      return () => {
        document.body.style.overflow = '';
        document.removeEventListener('keydown', handleKeyDown);
      };
    }
  }, [visible]);

  return ReactDOM.createPortal(
    <div className={styles.imagePreview} onClick={handleBackdropClick} style={{ zIndex: Z_INDEX }}>
      <div className={styles.imagePreviewContent}>
        <img src={src} alt="" className={styles.previewImage} />
        <Button
          type="text"
          className={styles.closeButton}
          onClick={onClose}
        >
          ×
        </Button>
      </div>
    </div>,
    document.body
  );
};

export const BtcFileThumbnailCell: React.FC<BtcFileThumbnailCellProps> = ({
  src = '',
  mime = '',
  originalName = '',
}) => {
  const [previewVisible, setPreviewVisible] = useState(false);

  const extension = useMemo(() => {
    const nameSource = originalName || src || '';
    const matched = nameSource.match(/\.([a-zA-Z0-9]+)(?:\?|#|$)/);
    return matched ? matched[1].toLowerCase() : '';
  }, [originalName, src]);

  const isImage = useMemo(() => {
    if (mime) {
      return mime.startsWith('image/');
    }
    const ext = extension;
    return ['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'bmp', 'ico'].includes(ext);
  }, [mime, extension]);

  const extensionLabel = useMemo(() => {
    if (!extension) {
      return 'FILE';
    }
    return extension.length > 4
      ? extension.slice(0, 4).toUpperCase()
      : extension.toUpperCase();
  }, [extension]);

  const typeClass = useMemo(() => {
    const ext = extension;
    if (['xls', 'xlsx', 'csv'].includes(ext)) return styles.iconExcel;
    if (['ppt', 'pptx'].includes(ext)) return styles.iconPpt;
    if (['doc', 'docx'].includes(ext)) return styles.iconWord;
    if (['pdf'].includes(ext)) return styles.iconPdf;
    if (['txt', 'md'].includes(ext)) return styles.iconText;
    return styles.iconDefault;
  }, [extension]);

  const getFileIcon = () => {
    const ext = extension;
    if (['xls', 'xlsx', 'csv'].includes(ext)) return <FileExcelOutlined />;
    if (['ppt', 'pptx'].includes(ext)) return <FilePptOutlined />;
    if (['doc', 'docx'].includes(ext)) return <FileWordOutlined />;
    if (['pdf'].includes(ext)) return <FilePdfOutlined />;
    if (['txt', 'md'].includes(ext)) return <FileTextOutlined />;
    return <FileOutlined />;
  };

  const openPreview = () => {
    if (!isImage || !src) return;
    setPreviewVisible(true);
  };

  return (
    <>
      <div className={styles.thumbnail}>
        {isImage ? (
          <div
            className={styles.image}
            role="button"
            tabIndex={0}
            onClick={openPreview}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                openPreview();
              }
            }}
          >
            <img src={src} alt="" />
          </div>
        ) : (
          <div className={`${styles.icon} ${typeClass}`}>
            <span className={styles.iconText}>{extensionLabel}</span>
          </div>
        )}
      </div>
      <ImagePreview
        visible={previewVisible}
        src={src}
        onClose={() => setPreviewVisible(false)}
      />
    </>
  );
};

// products/pc-admin/apps/system-app/src/components/btc-file-thumbnail-cell/BtcFileThumbnailCell.vue
<template>
  <div class="btc-file-thumbnail">
    <div
      v-if="isImage"
      class="btc-file-thumbnail__image"
      role="button"
      tabindex="0"
      @click.stop="openPreview"
      @keydown.enter.stop.prevent="openPreview"
    >
      <img :src="modelValue" alt="" />
    </div>
    <div v-else class="btc-file-thumbnail__icon" :class="typeClass">
      <span class="btc-file-thumbnail__icon-text">{{ extensionLabel }}</span>
    </div>
  </div>
  <teleport to="body">
    <el-image-viewer
      v-if="visible"
      :z-index="Z_INDEX"
      :url-list="previewList"
      :initial-index="0"
      @close="visible = false"
    />
  </teleport>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { ElImageViewer } from 'element-plus';

const props = withDefaults(
  defineProps<{
    modelValue?: string;
    mime?: string;
    originalName?: string;
  }>(),
  {
    modelValue: '',
    mime: '',
    originalName: '',
  }
);

const visible = ref(false);
const previewList = computed(() => (props.modelValue ? [props.modelValue] : []));
const Z_INDEX = 4000;

const extension = computed(() => {
  const nameSource = props.originalName || props.modelValue || '';
  const matched = nameSource.match(/\.([a-zA-Z0-9]+)(?:\?|#|$)/);
  return matched ? matched[1].toLowerCase() : '';
});

const isImage = computed(() => {
  if (props.mime) {
    return props.mime.startsWith('image/');
  }
  const ext = extension.value;
  return ['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'bmp', 'ico'].includes(ext);
});

const extensionLabel = computed(() => {
  if (!extension.value) {
    return 'FILE';
  }
  return extension.value.length > 4 ? extension.value.slice(0, 4).toUpperCase() : extension.value.toUpperCase();
});

const typeClass = computed(() => {
  const ext = extension.value;
  if (['xls', 'xlsx', 'csv'].includes(ext)) return 'btc-file-thumbnail__icon--excel';
  if (['ppt', 'pptx'].includes(ext)) return 'btc-file-thumbnail__icon--ppt';
  if (['doc', 'docx'].includes(ext)) return 'btc-file-thumbnail__icon--word';
  if (['pdf'].includes(ext)) return 'btc-file-thumbnail__icon--pdf';
  if (['txt', 'md'].includes(ext)) return 'btc-file-thumbnail__icon--text';
  return 'btc-file-thumbnail__icon--default';
});

const openPreview = () => {
  if (!isImage.value || !props.modelValue) return;
  visible.value = true;
};
</script>

<style scoped lang="scss">
.btc-file-thumbnail {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border-radius: 6px;
  background-color: var(--btc-color-fill-secondary, #f5f6f8);

  &__image {
    width: 100%;
    height: 100%;
    border-radius: 8px;
    overflow: hidden;
    cursor: zoom-in;
    background-color: rgba(0, 0, 0, 0.04);

    img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      display: block;
    }
  }

  &__icon {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
    border-radius: 8px;
    background-color: var(--btc-color-fill-secondary, #f0f2f5);
    color: var(--btc-color-text-secondary, #5c6273);
    font-weight: 600;
  }

  &__icon-text {
    font-size: 12px;
    letter-spacing: 0.5px;
  }

  &__icon--excel {
    background-color: rgba(40, 167, 69, 0.15);
    color: #28a745;
  }

  &__icon--ppt {
    background-color: rgba(255, 99, 71, 0.15);
    color: #ff6347;
  }

  &__icon--word {
    background-color: rgba(0, 123, 255, 0.15);
    color: #007bff;
  }

  &__icon--pdf {
    background-color: rgba(220, 53, 69, 0.15);
    color: #dc3545;
  }

  &__icon--text {
    background-color: rgba(108, 117, 125, 0.15);
    color: #6c757d;
  }

  &__icon--default {
    background-color: rgba(90, 98, 115, 0.12);
    color: #5a6273;
  }

  &__icon--image-fallback {
    background-color: rgba(0, 0, 0, 0.05);
    color: #8f95a1;
    font-size: 16px;
  }
}
</style>
