// products/pc-admin/apps/main-app/src/pages/login/footer/index.vue
<template>
  <div class="s-bottom-layer-content">
    <a href="https://about.bellis.com.cn" class="footer-link">关于我们</a>
    <a href="https://news.bellis.com.cn" class="footer-link">新闻动态</a>
    <a href="https://terms.bellis.com.cn" class="footer-link">服务条款</a>
    <a href="https://help.bellis.com.cn" class="footer-link">帮助中心</a>
    <!-- 企业服务暂时隐藏，保留逻辑 -->
    <a href="https://business.bellis.com.cn" class="footer-link" style="display: none;">企业服务</a>
    <a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener noreferrer" class="footer-link beian-link">
      桂ICP备2025062018号-1
    </a>
    <span class="copyright-text">
      {{ t('© {year} {appName}', { year: copyrightYear, appName: app.info.name }) }}
    </span>
  </div>
</template>

<script lang="ts" setup>
import dayjs from 'dayjs';

defineOptions({
  name: 'LoginFooter'
});

defineProps<{
  app: any;
  t: (key: string, params?: any) => string;
}>();

// 生成版权数据，从2012年到当前年份
const currentYear = dayjs().year();
const startYear = 2012;
const copyrightYear = currentYear > startYear ? `${startYear}-${currentYear}` : startYear.toString();
</script>

<style lang="scss">
@use './styles.scss';
</style>

// products/react-admin/apps/home-app/src/components/layout/Footer.tsx
import React, { useMemo } from 'react';
import { Link } from 'react-router-dom';
import styles from './Footer.module.scss';

export const Footer: React.FC = () => {
  const copyrightText = useMemo(() => {
    const currentYear = new Date().getFullYear();
    const startYear = 2012;
    const yearString = currentYear > startYear ? `${startYear}-${currentYear}` : startYear.toString();
    return `© ${yearString} BTC. All rights reserved.`;
  }, []);

  return (
    <footer className={styles.footer}>
      <div className={styles.bottomLayerContent}>
        <Link to="/about" className={styles.footerLink}>
          关于我们
        </Link>
        <Link to="/news" className={styles.footerLink}>
          新闻动态
        </Link>
        <Link to="/terms" className={styles.footerLink}>
          服务条款
        </Link>
        <Link to="/help" className={styles.footerLink}>
          帮助中心
        </Link>
        {/* Enterprise service is temporarily hidden */}
        <a
          href="https://beian.miit.gov.cn/"
          target="_blank"
          rel="noopener noreferrer"
          className={`${styles.footerLink} ${styles.beianLink}`}
        >
          桂ICP备2025062018号-1
        </a>
        <span className={styles.copyrightText}>{copyrightText}</span>
      </div>
    </footer>
  );
};

export default Footer;
