// products/react-admin/apps/admin-app/src/modules/access/views/perm-compose/components/BtcResourceTree.tsx
import React, { useState, useRef, useEffect, useCallback, forwardRef } from 'react';
import {
  Tree,
  Input,
  Switch,
  Tag,
} from '@enterprise-workspace/frontend/shared';
import { FolderOpenOutlined, SearchOutlined } from '@ant-design/icons';
import type { TreeProps, TreeNodeData } from '@enterprise-workspace/frontend/shared/data-display/Tree/types';
import styles from './BtcResourceTree.module.css';

interface ResourceTreeProps {
  resourceTree: any[];
  modelValue: {
    resourceFilterText: string;
    applyToChildren: boolean;
  };
  treeProps?: any;
  filterResourceNode: (value: string, data: any) => boolean;
  onResourceCheck?: (data: any, checked: boolean) => void;
}

export interface BtcResourceTreeRef {
  getCheckedNodes: () => any[];
  getCheckedKeys: () => number[];
  setCheckedKeys: (keys: number[]) => void;
  filter: (val: string) => void;
}

export const BtcResourceTree = forwardRef<BtcResourceTreeRef, ResourceTreeProps>(
  (
    {
      resourceTree,
      modelValue,
      treeProps = {
        children: 'children',
        label: 'resourceNameCn',
      },
      filterResourceNode,
      onResourceCheck,
    },
    ref
  ) => {
    const [filterText, setFilterText] = useState(modelValue.resourceFilterText);
    const [applyToChildren, setApplyToChildren] = useState(modelValue.applyToChildren);
    const treeComponentRef = useRef<any>(null);

    useEffect(() => {
      setFilterText(modelValue.resourceFilterText);
      setApplyToChildren(modelValue.applyToChildren);
    }, [modelValue]);

    useEffect(() => {
      if (filterText) {
        treeComponentRef.current?.filter(filterText);
      }
    }, [filterText]);

    // Expose methods through ref
    React.useImperativeHandle(
      ref,
      () => ({
        getCheckedNodes: () => treeComponentRef.current?.getCheckedNodes() || [],
        getCheckedKeys: () => treeComponentRef.current?.getCheckedKeys() || [],
        setCheckedKeys: (keys: number[]) => treeComponentRef.current?.setCheckedKeys(keys),
        filter: (val: string) => treeComponentRef.current?.filter(val),
      }),
      []
    );

    const handleCheck: TreeProps['onCheck'] = (checkedKeys, info) => {
      onResourceCheck?.(info.node, checkedKeys.checked);
    };

    const handleFilter: TreeProps['filterTreeNode'] = (node: TreeNodeData) => {
      return filterResourceNode(filterText, node);
    };

    const renderNode: TreeProps['render'] = (node: TreeNodeData) => {
      const data = node as any;
      return (
        <div className={styles.item}>
          <FolderOpenOutlined className={styles.itemIcon} />
          <span className={styles.itemLabel}>{data[treeProps.label]}</span>
          {data.supportedActions && (
            <Tag type="info" size="small" className={styles.itemTag}>
              {data.supportedActions.length}
            </Tag>
          )}
        </div>
      );
    };

    return (
      <div className={styles.scope}>
        <div className={styles.head}>
          <span className={styles.label}>资源列表</span>
          <Switch
            checked={applyToChildren}
            onChange={setApplyToChildren}
            checkedChildren="应用到子节点"
            unCheckedChildren=""
            size="small"
          />
        </div>

        <div className={styles.search}>
          <Input
            placeholder="搜索资源"
            prefix={<SearchOutlined />}
            value={filterText}
            onChange={(e) => setFilterText(e.target.value)}
            allowClear
            size="small"
          />
        </div>

        <div className={styles.data}>
          <Tree
            ref={treeComponentRef}
            data={resourceTree}
            treeProps={treeProps}
            checkable
            checkedKeys={modelValue.checkedKeys || []}
            onCheck={handleCheck}
            filterTreeNode={handleFilter}
            showIcon={false}
            defaultExpandAll
            checkStrictly={!applyToChildren}
            highlightCurrent
            render={renderNode}
            className={styles.tree}
          />
        </div>
      </div>
    );
  }
);

BtcResourceTree.displayName = 'BtcResourceTree';

export default BtcResourceTree;

// products/pc-admin/apps/admin-app/src/modules/access/views/perm-compose/components/BtcResourceTree.vue
﻿<template>
  <div class="scope">
    <!-- 资源标题 -->
    <div class="head">
      <el-text class="label">资源列表</el-text>
      <el-switch
        v-model="modelValue.applyToChildren"
        active-text="应用到子节点"
        inactive-text=""
        size="small"
      />
    </div>

    <!-- 资源搜索 -->
    <div class="search">
      <el-input
        v-model="modelValue.resourceFilterText"
        placeholder="搜索资源"
        clearable
        :prefix-icon="Search"
      />
    </div>

    <!-- 资源数据 -->
    <div class="data">
      <el-scrollbar>
        <el-tree
          ref="treeRef"
          class="tree"
          :data="resourceTree"
          :props="treeProps"
          :filter-node-method="filterResourceNode"
          show-checkbox
          :check-strictly="!modelValue.applyToChildren"
          node-key="id"
          default-expand-all
          highlight-current
          @check-change="$emit('resourceCheck', $event)"
        >
          <template #default="{ data }">
            <div class="item">
              <el-icon><FolderOpened /></el-icon>
              <el-text truncated class="item-label">
                {{ data.resourceNameCn }}
              </el-text>
              <el-tag v-if="data.supportedActions" size="small" type="info" class="item-tag">
                {{ data.supportedActions.length }}
              </el-tag>
            </div>
          </template>
        </el-tree>
      </el-scrollbar>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { FolderOpened, Search } from '@element-plus/icons-vue';

interface Props {
  resourceTree: any[];
  modelValue: {
    resourceFilterText: string;
    applyToChildren: boolean;
  };
  treeProps?: any;
  filterResourceNode: (value: string, data: any) => boolean;
}

const props = withDefaults(defineProps<Props>(), {
  treeProps: () => ({
    children: 'children',
    label: 'resourceNameCn',
  })
});

defineEmits<{
  resourceCheck: [data: any, checked: boolean];
}>();

defineOptions({
  name: 'BtcResourceTree'
});

const treeRef = ref();

watch(() => props.modelValue.resourceFilterText, (val) => {
  treeRef.value?.filter(val);
});

defineExpose({
  getCheckedNodes: () => treeRef.value?.getCheckedNodes(),
  getCheckedKeys: () => treeRef.value?.getCheckedKeys(),
  setCheckedKeys: (keys: number[]) => treeRef.value?.setCheckedKeys(keys),
  filter: (val: string) => treeRef.value?.filter(val),
});
</script>

<style lang="scss" scoped>
.scope {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 40px;
  font-size: 14px;
  padding: 0 10px;
  border-bottom: 1px solid var(--el-border-color-extra-light);
  flex-shrink: 0;

  .label {
    flex: 1;
    font-weight: 500;
  }
}

.search {
  padding: 10px;
  border-bottom: 1px solid var(--el-border-color-extra-light);
  flex-shrink: 0;

  :deep(.el-input__wrapper) {
    border-radius: 6px;
  }
}

.data {
  flex: 1;
  overflow: hidden;
  box-sizing: border-box;

  .tree {
    :deep(.el-tree-node__content) {
      height: 38px;
      margin: 0 5px;
    }

    .item {
      display: flex;
      align-items: center;
      gap: 8px;
      flex: 1;
      overflow: hidden;

      .el-icon {
        flex-shrink: 0;
        color: var(--el-color-primary);
      }

      .item-label {
        flex: 1;
        min-width: 0;
      }

      .item-tag {
        flex-shrink: 0;
        font-size: 11px;
      }

      &.is-active {
        color: var(--el-color-primary);
        font-weight: 500;
      }
    }
  }
}
</style>
