// products/pc-admin/apps/admin-app/src/modules/access/views/perm-compose/components/BtcActionTable.vue
﻿<template>
  <div class="data">
    <el-scrollbar>
      <!-- 组合模式表格 -->
      <el-table
        v-if="mode === 'compose'"
        ref="tableRef"
        :data="filteredActions"
        border
        stripe
        @selection-change="$emit('actionSelectionChange', $event)"
        style="width: 100%;"
      >
        <el-table-column type="selection" width="50" :selectable="(row) => isActionSupported(row.id)" />
        <el-table-column label="图标" width="60" align="center">
          <template #default="{ row }">
            <el-icon v-if="row.actionCode === 'view'" :size="18" color="var(--el-color-success)"><View /></el-icon>
            <el-icon v-else-if="row.actionCode === 'create'" :size="18" color="var(--el-color-primary)"><Plus /></el-icon>
            <el-icon v-else-if="row.actionCode === 'edit'" :size="18" color="var(--el-color-warning)"><Edit /></el-icon>
            <el-icon v-else-if="row.actionCode === 'delete'" :size="18" color="var(--el-color-danger)"><Delete /></el-icon>
            <el-icon v-else :size="18"><Operation /></el-icon>
          </template>
        </el-table-column>
        <el-table-column prop="actionNameCn" label="名称" width="80" />
        <el-table-column prop="actionCode" label="编码" min-width="100">
          <template #default="{ row }">
            <code class="action-code">{{ row.actionCode }}</code>
          </template>
        </el-table-column>
        <el-table-column label="方法" width="90" align="center">
          <template #default="{ row }">
            <el-tag size="small" :type="getMethodType(row.httpMethod)" effect="plain">
              {{ row.httpMethod }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="支持度" width="90" align="center" v-if="selectedResources.length > 1">
          <template #default="{ row }">
            <el-tooltip :content="`${getActionSupportCount(row.id)} / ${selectedResources.length} 个资源支持`" placement="top">
              <el-tag
                size="small"
                :type="getActionSupportCount(row.id) === selectedResources.length ? 'success' : 'warning'"
                effect="plain"
              >
                {{ getActionSupportCount(row.id) }}/{{ selectedResources.length }}
              </el-tag>
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>

      <!-- 矩阵模式表格 -->
      <div v-if="matrixData.length === 0 && mode === 'matrix'" class="matrix-empty">
        <el-empty description="请先选择资源">
          <template #image>
            <el-icon :size="60" color="var(--el-text-color-placeholder)">
              <FolderOpened />
            </el-icon>
          </template>
        </el-empty>
      </div>
      <el-table
        v-else-if="mode === 'matrix'"
        :data="matrixData"
        border
        stripe
        highlight-current-row
        style="width: 100%;"
      >
        <el-table-column prop="resourceNameCn" label="资源" width="220" fixed align="center" header-align="center">
          <template #default="{ row }">
            <div class="matrix-resource">
              <el-icon :size="16"><FolderOpened /></el-icon>
              <span>{{ row.resourceNameCn }}</span>
              <el-tag v-if="row.resourceCode" size="small" type="info">
                {{ row.resourceCode }}
              </el-tag>
            </div>
          </template>
        </el-table-column>
        <el-table-column
          v-for="action in actions"
          :key="action.id"
          :prop="`action_${action.id}`"
          min-width="100"
          align="center"
        >
          <template #header>
            <div class="matrix-action-header">
              <el-icon v-if="action.actionCode === 'view'" :size="16" color="var(--el-color-success)"><View /></el-icon>
              <el-icon v-else-if="action.actionCode === 'create'" :size="16" color="var(--el-color-primary)"><Plus /></el-icon>
              <el-icon v-else-if="action.actionCode === 'edit'" :size="16" color="var(--el-color-warning)"><Edit /></el-icon>
              <el-icon v-else-if="action.actionCode === 'delete'" :size="16" color="var(--el-color-danger)"><Delete /></el-icon>
              <span>{{ action.actionNameCn }}</span>
            </div>
          </template>
          <template #default="{ row }">
            <el-checkbox
              :model-value="isPermissionChecked(row.id, action.id)"
              @change="handleMatrixToggle(row.id, action.id, $event)"
              :disabled="!isActionSupportedByResource(row.id, action.id)"
            />
          </template>
        </el-table-column>
      </el-table>
    </el-scrollbar>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { View, Plus, Edit, Delete, Operation, FolderOpened } from '@element-plus/icons-vue';

interface Props {
  mode: 'matrix' | 'compose';
  filteredActions: any[];
  matrixData: any[];
  actions: any[];
  selectedResources: number[];
  isActionSupported: (actionId: number) => boolean;
  getActionSupportCount: (actionId: number) => number;
  isPermissionChecked: (resourceId: number, actionId: number) => boolean;
  isActionSupportedByResource: (resourceId: number, actionId: number) => boolean;
  getMethodType: (method: string) => string;
  handleMatrixToggle: (resourceId: number, actionId: number, checked: boolean | string | number) => void;
}

const props = defineProps<Props>();

defineEmits<{
  actionSelectionChange: [selection: any[]];
}>();

defineOptions({
  name: 'BtcActionTable'
});

const tableRef = ref();

defineExpose({
  clearSelection: () => tableRef.value?.clearSelection(),
  toggleRowSelection: (row: any, checked: boolean) => tableRef.value?.toggleRowSelection(row, checked),
});
</script>

<style lang="scss" scoped>
.data {
  flex: 1;
  overflow: hidden;
  box-sizing: border-box;
}

.action-code {
  font-size: 12px;
  color: var(--el-color-primary);
  font-family: 'Consolas', 'Monaco', monospace;
  background: var(--el-color-primary-light-9);
  padding: 2px 6px;
  border-radius: 3px;
}

.matrix-empty {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 400px;
  padding: 40px;
}

.matrix-resource {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;

  .el-icon {
    color: var(--el-color-primary);
    flex-shrink: 0;
  }

  span {
    font-size: 13px;
    font-weight: 500;
  }

  .el-tag {
    font-size: 11px;
    flex-shrink: 0;
  }
}

.matrix-action-header {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;

  .el-icon {
    flex-shrink: 0;
  }

  span {
    font-size: 12px;
    font-weight: 500;
  }
}

:deep(.el-table) {
  font-size: 13px;

  .el-checkbox {
    display: flex;
    justify-content: center;
  }

  .el-table__cell {
    padding: 10px 0;
  }

  th.el-table__cell {
    background-color: var(--el-fill-color-lighter);
  }
}

:deep(.el-empty) {
  padding: 40px 0;
}
</style>

// products/react-admin/apps/admin-app/src/modules/access/views/perm-compose/components/BtcActionTable.tsx
import React, { useState, useRef, useCallback } from 'react';
import type { TableColumnsType } from 'antd';
import {
  AppTable,
  Tag,
  Checkbox,
  Empty,
} from '@enterprise-workspace/frontend/shared';
import {
  EyeOutlined,
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  SettingOutlined,
  FolderOpenOutlined,
} from '@ant-design/icons';
import type { AppTableRef } from '@enterprise-workspace/frontend/shared/data-display/Table/types';
import styles from './BtcActionTable.module.css';

interface BtcActionTableProps {
  mode: 'matrix' | 'compose';
  filteredActions: any[];
  matrixData: any[];
  actions: any[];
  selectedResources: number[];
  isActionSupported: (actionId: number) => boolean;
  getActionSupportCount: (actionId: number) => number;
  isPermissionChecked: (resourceId: number, actionId: number) => boolean;
  isActionSupportedByResource: (resourceId: number, actionId: number) => boolean;
  getMethodType: (method: string) => string;
  handleMatrixToggle: (resourceId: number, actionId: number, checked: boolean | string | number) => void;
  onActionSelectionChange?: (selection: any[]) => void;
}

const getActionIcon = (actionCode: string, size: number = 18) => {
  const iconStyle = { fontSize: size };
  switch (actionCode) {
    case 'view':
      return <EyeOutlined style={{ ...iconStyle, color: 'var(--color-success)' }} />;
    case 'create':
      return <PlusOutlined style={{ ...iconStyle, color: 'var(--color-primary)' }} />;
    case 'edit':
      return <EditOutlined style={{ ...iconStyle, color: 'var(--color-warning)' }} />;
    case 'delete':
      return <DeleteOutlined style={{ ...iconStyle, color: 'var(--color-danger)' }} />;
    default:
      return <SettingOutlined style={iconStyle} />;
  }
};

export const BtcActionTable: React.FC<BtcActionTableProps> & {
  displayName: string;
} = ({
  mode,
  filteredActions,
  matrixData,
  actions,
  selectedResources,
  isActionSupported,
  getActionSupportCount,
  isPermissionChecked,
  isActionSupportedByResource,
  getMethodType,
  handleMatrixToggle,
  onActionSelectionChange,
}) => {
  const tableRef = useRef<AppTableRef>(null);
  const [selection, setSelection] = useState<any[]>([]);

  const handleSelectionChange = useCallback((newSelection: any[]) => {
    setSelection(newSelection);
    onActionSelectionChange?.(newSelection);
  }, [onActionSelectionChange]);

  // Compose mode table columns
  const composeColumns: TableColumnsType<any> = [
    {
      title: '',
      width: 50,
      render: (_, record) => (
        <Checkbox
          checked={isActionSupported(record.id)}
          disabled={!isActionSupported(record.id)}
        />
      ),
    },
    {
      title: '图标',
      width: 60,
      align: 'center',
      render: (_, record) => getActionIcon(record.actionCode),
    },
    {
      title: '名称',
      dataIndex: 'actionNameCn',
      width: 80,
    },
    {
      title: '编码',
      dataIndex: 'actionCode',
      minWidth: 100,
      render: (_, record) => (
        <code className={styles.actionCode}>{record.actionCode}</code>
      ),
    },
    {
      title: '方法',
      width: 90,
      align: 'center',
      render: (_, record) => (
        <Tag
          type={getMethodType(record.httpMethod)}
          variant="plain"
          size="small"
        >
          {record.httpMethod}
        </Tag>
      ),
    },
  ];

  if (selectedResources.length > 1) {
    composeColumns.push({
      title: '支持度',
      width: 90,
      align: 'center',
      render: (_, record) => {
        const supportCount = getActionSupportCount(record.id);
        const isFullSupported = supportCount === selectedResources.length;
        return (
          <Tag
            type={isFullSupported ? 'success' : 'warning'}
            variant="plain"
            size="small"
          >
            {supportCount}/{selectedResources.length}
          </Tag>
        );
      },
    });
  }

  // Matrix mode columns
  const matrixColumns: TableColumnsType<any> = [
    {
      title: '资源',
      dataIndex: 'resourceNameCn',
      width: 220,
      fixed: 'left',
      align: 'center',
      render: (_, record) => (
        <div className={styles.matrixResource}>
          <FolderOpenOutlined style={{ fontSize: 16 }} />
          <span>{record.resourceNameCn}</span>
          {record.resourceCode && (
            <Tag type="info" size="small">
              {record.resourceCode}
            </Tag>
          )}
        </div>
      ),
    },
    ...actions.map((action) => ({
      title: (
        <div className={styles.matrixActionHeader}>
          {getActionIcon(action.actionCode, 16)}
          <span>{action.actionNameCn}</span>
        </div>
      ),
      dataIndex: `action_${action.id}`,
      align: 'center',
      render: (_: boolean, record: any) => (
        <Checkbox
          checked={isPermissionChecked(record.id, action.id)}
          disabled={!isActionSupportedByResource(record.id, action.id)}
          onChange={(e) => handleMatrixToggle(record.id, action.id, e.target.checked)}
        />
      ),
    })),
  ];

  return (
    <div className={styles.data}>
      <div className={styles.tableContainer}>
        {mode === 'compose' && (
          <AppTable
            ref={tableRef as React.RefObject<AppTableRef>}
            dataSource={filteredActions}
            columns={composeColumns}
            rowKey="id"
            pagination={false}
            className={styles.composeTable}
          />
        )}

        {mode === 'matrix' && matrixData.length === 0 && (
          <div className={styles.matrixEmpty}>
            <Empty
              description="请先选择资源"
              image={FolderOpenOutlined}
              imageSize={60}
            />
          </div>
        )}

        {mode === 'matrix' && matrixData.length > 0 && (
          <AppTable
            dataSource={matrixData}
            columns={matrixColumns}
            rowKey="id"
            pagination={false}
            className={styles.matrixTable}
            scroll={{ x: true }}
          />
        )}
      </div>
    </div>
  );
};

BtcActionTable.displayName = 'BtcActionTable';

export default BtcActionTable;
