// products/react-admin/apps/logistics-app/src/components/btc-file-actions-cell/BtcFileActionsCell.tsx
import React from 'react';
import { Button } from '@enterprise-workspace/frontend/shared';
import styles from './BtcFileActionsCell.module.scss';

export interface BtcFileActionsCellRow {
  [key: string]: unknown;
}

export interface BtcFileActionsCellProps {
  row: BtcFileActionsCellRow;
  onShare?: (row: BtcFileActionsCellRow) => void;
  onDetail?: (row: BtcFileActionsCellRow) => void;
  onDelete?: (row: BtcFileActionsCellRow) => void;
}

export const BtcFileActionsCell: React.FC<BtcFileActionsCellProps> = ({
  row,
  onShare,
  onDetail,
  onDelete,
}) => {
  const handleShare = () => {
    onShare?.(row);
  };

  const handleDetail = () => {
    onDetail?.(row);
  };

  const handleDelete = () => {
    onDelete?.(row);
  };

  return (
    <div className={styles.tableOp}>
      <Button type="link" onClick={handleShare} danger={false}>
        分享
      </Button>
      <Button type="link" onClick={handleDetail} danger={false}>
        详情
      </Button>
      <Button type="link" onClick={handleDelete} danger>
        删除
      </Button>
    </div>
  );
};

// products/pc-admin/apps/logistics-app/src/components/btc-file-actions-cell/BtcFileActionsCell.vue
<template>
  <div class="btc-table-op">
    <el-button text type="success" @click="handleShare">
      分享
    </el-button>
    <el-button text type="primary" @click="handleDetail">
      详情
    </el-button>
    <el-button text type="danger" @click="handleDelete">
      删除
    </el-button>
  </div>
</template>

<script setup lang="ts">

const props = withDefaults(
  defineProps<{
    row: Record<string, any>;
    onShare?: (row: Record<string, any>) => void;
    onDetail?: (row: Record<string, any>) => void;
    onDelete?: (row: Record<string, any>) => void;
  }>(),
  {
    row: () => ({}),
    onShare: undefined,
    onDetail: undefined,
    onDelete: undefined,
  }
);

const handleShare = () => {
  props.onShare?.(props.row);
};

const handleDetail = () => {
  props.onDetail?.(props.row);
};

const handleDelete = () => {
  props.onDelete?.(props.row);
};
</script>

<style scoped lang="scss"></style>
